language: ruby
rvm:
  - "1.9.3"
branches:
  only:
    - travis
env:
  global:
    - secure: "jfVZGDZffFqB6t8OGyWFU1jPm8Pps6Pzl00jKpwmtfRVoJ2ww+tse19LlW0L\nz2sc1H1G88YMZua84TYF4vLK/q+Yg1Wc02anqUD66gQyL1r20ug6HAbnku0t\nUEzXzkWGBECusmbvFvLB0+uW1zLwV225SsZZMzEAxn1RAwSW7JA="
notifications:
  campfire: siyelo:$CAMPFIRE_TOKEN@289236
before_script:
  # Use Google's name servers. The default name servers cannot
  # resolve capybara1.elabs.se for unknown reasons.
  - sudo su -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf; echo "nameserver 8.8.4.4" >> /etc/resolv.conf'

  # install phantomjs
  - version=phantomjs-1.7.0-linux-i686
  - wget http://phantomjs.googlecode.com/files/$version.tar.bz2
  - tar xjf $version.tar.bz2
  - mv $version phantomjs
  - "export PATH=phantomjs/bin:$PATH"
  - phantomjs --version

  # setup database
  - psql -c 'create database hrt_test;' -U postgres
  - "cp config/database.yml.travis config/database.yml"
  - "rake db:migrate"

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
