language: ruby
rvm:
  - "1.9.3"
branches:
  only:
    - travis
before_script:
  - psql -c 'create database hrt_test;' -U postgres
  - "cp config/database.yml.travis config/database.yml"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
